services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: notes
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
