services:
    app:
        build:
            context: .
        ports:
            - "8001:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        env_file:
            - .env.docker

    mysql:
        image: mysql:8
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: notes
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - .env.docker

volumes:
    db-data:
